### PR TITLE
Release/3.10.3

### PR DESCRIPTION
**Pull request by thoma202**

### CODE REVIEW

**Comment by thoma202** [comment]
Disable logs
Fix javascript that was throwing syntax error when HTML Minification is on
Modify address in PayPal if user uses Express Checkout Shortcut
If user changes address in PayPal with Express Checkout Shortcut : address is modified in PrestaShop
Remove PHP Warnings
Fix if a minimal quantity exists on a product and using express checkout shortcut
Verify merchant id exists when using context checkout

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Please note that #28 will be included with this new version. However, what about #27 ?

Thanks for your answer

**Comment by Quetzacoalt91** [comment]
Please do not forget to update the version in the file config.xml

**Comment by thoma202** [comment]
Hi @Quetzacoalt91 

Sorry for the long wait, we were not sur if we were abble to add the next version into this one or not. 
Can you please Merge this PR with #28 and #27  ? 

Thanks

**Comment by Quetzacoalt91** [comment]
Regarding the last commit, we need to validate a new time what has been included.
We keep you in touch.

Best regards

**Comment by thoma202** [comment]
Please see #34

**Pull request closed without merging**
