### PR TITLE
Release/3.10.2

### PR DESCRIPTION
**Pull request by thoma202**
Added logos for mobile express checkout (they had been deleted because of a gitignore in May)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Ready to merge this PR. Can you also have a look on #22 please ?

**Comment by thoma202** [comment]
Hi @Quetzacoalt91 

Ok for me for #22 also. 
Can you merge this on Monday ? 

Thanks

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Sorry but I will be out of office for the next 2 weeks.

@tchauviere will handle it.

**Comment by thoma202** [comment]
All right, 

@tchauviere can you merge this PR and PR #22 on Monday ? 
@Quetzacoalt91 : I hope you'll have great holidays.

**Comment by tchauviere** [comment]
Hi @thoma202,

Sorry for the little delay. Everything is merged and up to date by now.

Best regards,

**Pull request merged**
