### PR TITLE
Release/3.9.0

### PR DESCRIPTION
**Pull request by thoma202**
Germany specific support 
Possibility to do Partial capture

### CODE REVIEW

**Comment by gaillafr** [comment]
This PR is not valid.
Many errors are thrown via the validator and many of these could be fixed easily.

Thank you, kind regards.

**Comment by thoma202** [comment]
Hi, 
We fixed most of the errors we had, only the paypal.gif in root (I think this is needed for 1.4, isn't it ?) and double quotes to single quotes changes. 

Is it ok for you ? 
Thoma

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

I'm ready to merge this PR. Let me know when I can do it.

Best regards

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

As planned, your PR has just been merged, and the changes should be available from tomorrow.

Best regards

**Pull request merged**
