### PR TITLE
Release/3.10.0

### PR DESCRIPTION
**Pull request by thoma202**
- In context Checkout feature
- Show shipping address when coming back from Express Checkout Shortcut.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi,

Here are few notices to fix on the configuration page, which appear right after the upgrade:

capture du 2015-06-30 11 47 53

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Have you noticed the message saying that a template is missing ?
You can see it on every page of the front office.

```
<script type="text/javascript">No template found for module paypal</script>
```

**Comment by thoma202** [comment]
Hi @Quetzacoalt91 
Thanks for your feedback, We've must have introduce this little bug when fixing structure issues thrown by the validator. 
I've just fixed it.

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Thanks, I have just tested the PR and having the proper shipping address is really better.
But because I need a Pro PayPal account, I could not test the _In context Checkout_ feature.In consequence, I will have to trust your changes.

Let me know when I can merge it.

Best regards

**Comment by thoma202** [comment]
Hi @Quetzacoalt91 

Thanks, you can merge the PR on Monday, this would be great. 
Thanks

**Comment by Quetzacoalt91** [comment]
Hi @thoma202,

Thanks, your PR has just been merged and the changes will be available from tomorrow.

Best regards

**Pull request merged**
